templates:
  breaking_news:
    file: "breaking_news.png"
    dimensions: [1080, 1350]
    text_areas:
      headline:
        position: [50, 200]
        max_width: 980
        font_size: 48
        font_weight: "bold"
        color: "#FFFFFF"
        background_color: "#FF0000"
        padding: 20
        
      summary:
        position: [50, 400]
        max_width: 980
        font_size: 32
        color: "#FFFFFF"
        line_height: 1.4
        
      source:
        position: [50, 1200]
        font_size: 24
        color: "#CCCCCC"
        
      timestamp:
        position: [50, 1250]
        font_size: 20
        color: "#CCCCCC"
        
  analysis_post:
    file: "analysis_post.png"
    dimensions: [1080, 1350]
    text_areas:
      headline:
        position: [50, 150]
        max_width: 980
        font_size: 42
        font_weight: "bold"
        color: "#1A1A1A"
        
      summary:
        position: [50, 300]
        max_width: 980
        font_size: 28
        color: "#333333"
        line_height: 1.5
        
      key_points:
        position: [50, 600]
        max_width: 980
        font_size: 24
        color: "#555555"
        line_height: 1.6
        
      source:
        position: [50, 1200]
        font_size: 22
        color: "#666666"
        
  feature_story:
    file: "feature_story.png"
    dimensions: [1080, 1350]
    text_areas:
      category:
        position: [50, 100]
        font_size: 28
        font_weight: "bold"
        color: "#0066CC"
        
      headline:
        position: [50, 180]
        max_width: 980
        font_size: 40
        font_weight: "bold"
        color: "#1A1A1A"
        line_height: 1.3
        
      summary:
        position: [50, 400]
        max_width: 980
        font_size: 26
        color: "#333333"
        line_height: 1.5
        
      source:
        position: [50, 1200]
        font_size: 22
        color: "#666666"
        
      timestamp:
        position: [50, 1250]
        font_size: 18
        color: "#888888"

fonts:
  primary: "Arial"
  secondary: "Helvetica"
  fallback: "sans-serif"
  
colors:
  breaking: "#FF0000"
  analysis: "#0066CC"
  feature: "#00AA44"
  text_primary: "#1A1A1A"
  text_secondary: "#333333"
  text_muted: "#666666"
  background: "#FFFFFF"
  
branding:
  logo_position: [900, 50]
  logo_size: [150, 50]
  watermark_opacity: 0.7
