name: Daily News Instagram Automation

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  daily-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Setup Instagram session from secrets
      run: |
        echo '${{ secrets.INSTAGRAM_SESSION_DATA }}' > instagram_session.json
        ls -la instagram_session.json
        echo "✅ Instagram session file created from secrets"
    
    - name: Cache Instagram session
      uses: actions/cache@v4
      with:
        path: instagram_session.json
        key: instagram-session-${{ secrets.INSTAGRAM_USERNAME }}-v3
        restore-keys: |
          instagram-session-${{ secrets.INSTAGRAM_USERNAME }}-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Run daily automation
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL || 'sqlite:////tmp/news_instagram.db' }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python deploy/github_automation.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: automation-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
    
    - name: Automation Success Summary
      if: success()
      run: |
        echo "✅ Daily automation completed successfully! 🎉"
        echo "$(date): News scraping and Instagram posting completed"
        echo "Check the logs above for detailed results"
    
    - name: Automation Failure Summary
      if: failure()
      run: |
        echo "❌ Daily automation failed"
        echo "$(date): Check the logs above for error details"
        echo "The system will retry tomorrow at the scheduled time"
