name: Debug Environment Variables

on:
  workflow_dispatch:

jobs:
  debug-env:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check Environment Variables
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "=== ENVIRONMENT VARIABLE DEBUG ==="
        echo "INSTAGRAM_USERNAME length: ${#INSTAGRAM_USERNAME}"
        echo "INSTAGRAM_PASSWORD length: ${#INSTAGRAM_PASSWORD}"
        echo "GEMINI_API_KEY length: ${#GEMINI_API_KEY}"
        
        if [ -z "$INSTAGRAM_USERNAME" ]; then
          echo "❌ INSTAGRAM_USERNAME is empty or not set"
        else
          echo "✅ INSTAGRAM_USERNAME is set"
        fi
        
        if [ -z "$INSTAGRAM_PASSWORD" ]; then
          echo "❌ INSTAGRAM_PASSWORD is empty or not set"
        else
          echo "✅ INSTAGRAM_PASSWORD is set"
        fi
        
        if [ -z "$GEMINI_API_KEY" ]; then
          echo "❌ GEMINI_API_KEY is empty or not set"
        else
          echo "✅ GEMINI_API_KEY is set"
        fi
        
        echo "=== PYTHON ENVIRONMENT CHECK ==="
        python3 -c "
        import os
        print(f'Python INSTAGRAM_USERNAME: {len(os.environ.get(\"INSTAGRAM_USERNAME\", \"\"))} chars')
        print(f'Python INSTAGRAM_PASSWORD: {len(os.environ.get(\"INSTAGRAM_PASSWORD\", \"\"))} chars')
        print(f'Python GEMINI_API_KEY: {len(os.environ.get(\"GEMINI_API_KEY\", \"\"))} chars')
        "
        
    - name: List All Environment Variables
      run: |
        echo "=== ALL ENV VARS (filtered) ==="
        env | grep -E "INSTAGRAM|GEMINI" || echo "No matching environment variables found"
