name: Manual News Automation

on:
  workflow_dispatch:
    inputs:
      posts_count:
        description: 'Number of posts to generate'
        required: false
        default: '3'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '5'
      template_type:
        description: 'Template type to use'
        required: false
        default: 'mixed'
        type: choice
        options:
        - 'mixed'
        - 'breaking'
        - 'analysis'
        - 'feature'
      immediate_publish:
        description: 'Publish immediately?'
        required: false
        default: false
        type: boolean

jobs:
  manual-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Run manual automation
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTS_COUNT: ${{ github.event.inputs.posts_count }}
        TEMPLATE_TYPE: ${{ github.event.inputs.template_type }}
        IMMEDIATE_PUBLISH: ${{ github.event.inputs.immediate_publish }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python deploy/manual_automation.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: manual-automation-logs-${{ github.run_number }}
        path: logs/
        retention-days: 7
    
    - name: Manual Automation Summary
      if: always()
      run: |
        echo "🎯 Manual automation completed!"
        echo ""
        echo "**Parameters:**"
        echo "- Posts: ${{ github.event.inputs.posts_count }}"
        echo "- Template: ${{ github.event.inputs.template_type }}"
        echo "- Immediate Publish: ${{ github.event.inputs.immediate_publish }}"
        echo ""
        echo "**Status:** ${{ job.status }}"
        echo "**Timestamp:** $(date)"
