name: Test Automation

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'basic'
        type: choice
        options:
        - 'basic'
        - 'scraping-only'
        - 'generation-only'

permissions:
  contents: read
  actions: read

jobs:
  test-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TEST_TYPE: ${{ github.event.inputs.test_type }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python deploy/test_automation.py
    
    - name: Test Results Summary
      if: always()
      run: |
        echo "🧪 **Test Results Summary**"
        echo "**Test Type:** ${{ github.event.inputs.test_type }}"
        echo "**Status:** ${{ job.status }}"
        echo "**Timestamp:** $(date)"
        echo "Check the workflow logs above for detailed results."
